### ISSUE TITLE
Icons Missing

### ISSUE THREAD

**Issue by Kaperios** [Pipshag/dotfiles_nord#1]
So I couldn't find any other way to contact you, so decided to create an issue that you might notice. I'm really enjoying the waybar config you created, but have an issue with quite a few icons missing and can't find out which fonts would contain them. Would you mind dropping here all the fonts you've used for your config or which fonts might contain all the icons you've used?

**Comment by Pipshag** [comment]
No worries!
I thought I only used free fonts, but it seems that I mixed in some Font Awesome Pro fonts as well (for example [space cat](https://fontawesome.com/v5.15/icons/cat-space?style=solid) & [duck](https://fontawesome.com/v5.15/icons/duck?style=solid])).

**Comment by Pipshag** [comment]
If you need some more inspiration I continued to work on [dotfiles_gruvbox](https://github.com/Pipshag/dotfiles_gruvbox) with some more scripts and functions. It's based on the **dotfiles_nord** configs so you should be able to extend it easily if you find anything you like.
